Table schedule {
  id         serial [pk]
  frequency  text // 'monthly' | 'yearly'
}

Table question_schedule {
  id            serial [pk]
  schedule_id   int [ref: > schedule.id]
  question_id   int [ref: > question.id]
  rotation_group text // nullable, ex) 'setA','setB'
}