Table session {
  id           serial [pk]
  user_id      int [ref: > user.id]
  period_month int
  period_year  int
  type         text // 'monthly' | 'yearly'
  started_at   timestamptz [default: `now()`]
  completed_at timestamptz
}

Table response {
  id                   serial [pk]
  session_id           int [ref: > session.id]
  question_version_id  int [ref: > question_version.id]
  created_at           timestamptz [default: `now()`]
  raw                  jsonb  
  score                numeric 
}

Table response_index {
  id           serial [pk]
  session_id   int [ref: > session.id]
  user_id      int [ref: > user.id]
  question_code text
  period_month  int
  period_year   int
}